version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Python uv
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # npm
  - package-ecosystem: npm
    directory: /webui
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Docker
  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
